### ISSUE TITLE
这个不能动态改变阴影颜色啊

### ISSUE THREAD

**Issue by dazeGitHub** [lijiankun24/ShadowLayout#4]
这个不能代码动态改变阴影颜色啊，我这么写也不好使：  
  public void setShadowColor(int shadowColor) {
        mPaint.setShadowLayer(mShadowRadius, mShadowDx, mShadowDy, shadowColor);
        invalidate();
    }

**Comment by lijiankun24** [comment]
是可以的，需要注意的是，在设置颜色的时候，需要给颜色设置透明度。

**Comment by lijiankun24** [comment]
现在用新版本的 ShadowLayout 是可以的了，需要注意的是，在设置颜色的时候，需要给颜色设置透明度。
