### ISSUE TITLE
library SDK版本设置那么高干嘛？

### ISSUE THREAD

**Issue by Hiboboo** [lijiankun24/ShadowLayout#5]
library的SDK版本设置的太高了，都是26的，可我们项目得用25才可以，肯定有些人的版本更低，这就尴尬了，想用，用不成

**Comment by asker517** [comment]
@Hiboboo 人家miniSdk不是15么....`compileSdkVersion` 才是26 ..这会影响你项目??

**Comment by Hiboboo** [comment]
@asker517 就是因为compileSdkVersion这个版本太高了。
![image](https://user-images.githubusercontent.com/11403290/35368007-39739a7a-01bc-11e8-9687-4bf09f85dfa2.png)
我这项目里只能使用25，你的是26，冲突了，我还得把你的代码Down到我本地再加入，好麻烦的

**Comment by asker517** [comment]
@Hiboboo 这不是我的代码,哈哈 只是看到了你的问题,我觉得还是建议你们提高一下自己工程的complileSdkVersion. support版本也该更新了..理论上应该保证complileSdkVersion为最新的,才能保证能在最新android系统上没问题. 一般都是miniSDK可能限制你的使用,很少有人家complileSdkVersion限制的

**Comment by Hiboboo** [comment]
@asker517 你看到的貌似确实是我代码的问题。但是这实际上是由于引入你的library后才导致这种错误。
首先，我的项目中有特殊的需求，不容许SDK的版本过高，无法保持到最新版本，这个理论我是非常清楚的。
然后就是，由于你的library中SDK版本定义在了26，又同时引入了support-v26的支持库，因此，在我们引用你的library后，就会出现这种问题。
最后，你说的不无道理，但如果做library开源，是不是该考虑一下向下兼容性的问题？

你的这个库可能会解决我项目中的一个问题，但我现在不得不使用最土鳖的方法来引用。而你的Maven作用就很小了。

友情建议而已。
我现在已经Down了你的源码，谢谢了。

**Comment by asker517** [comment]
啊哈 解决了就好..再次说一下..这不是我写的代码 是人家大神的.

在 2018年1月25日 上午10:59，Hiboboo <notifications@github.com>写道：

**Comment by lijiankun24** [comment]
@Hiboboo 导致那个问题的原因应该是引入了 “support-v26的支持库” ，而不是因为“complileSdkVersion是26”吧

**Comment by Hiboboo** [comment]
@asker517 哈哈哈，我一直以为是你的代码了。
@lijiankun24 对，应该是support引起的，不确定complileSDK会不会影响

**Comment by lijiankun24** [comment]
嗯，谢谢你的建议，最近正打算抽时间更新一个版本呢

**Comment by lijiankun24** [comment]
@Hiboboo 嗯，谢谢你的建议，最近正打算抽时间更新一个版本呢
@asker517 感谢对这个库的关注~
