### ISSUE TITLE
onMeasure 测量时的一个问题

### ISSUE THREAD

**Issue by zxxf18** [lijiankun24/ShadowLayout#9]
作者代码的onMeasure中

```
 protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
         ……
         //计算padding
}
```

计算测量的顺序是，先进行一次测量  super.onMeasure ，然后设置padding，再进行后续的布局和绘制，但是在这个过程可能会出现 当内部控件有包含圆角的布局时（不知道别的会不会出现，我是这里发现的），漏测了圆角的距离，即：corners android:
radius="..." 。导致后续绘制时出圆角不见的错误

这个错误并不是必现，不过我这里出现频率挺高，分析一下没出现的情况是某些地方自动触发了整个view的二次测量，所以这里修改 onMeasure 为如下，就可避免
```
 protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
         ……
         //计算padding
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
}
```

实验是在华为M3平板，android7.0上进行的，希望作者可以关注下

**Comment by lijiankun24** [comment]
十分感谢 @zxxf18
